#! /bin/sh

## STARTUP ##

pulseaudio &
picom -fb &
sxhkd &
nitrogen --restore
setxkbmap -option caps:escape_shifted_capslock &
mpris-proxy &
$HOME/.config/polybar/shapes/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5


## WINDOW CONFIGUARTION ##


bspc config border_width       0
bspc config window_gap         5
bspc config bottom_padding     0
bspc config top_padding	       31	

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####


bspc config normal_border_color         "#51576d"
bspc config active_border_color         "#babbf1"
bspc config focused_border_color        "#babbf1"
bspc config presel_feedback_color       "#babbf1"
bspc config urgent_border_color         "#babbf1"



## APPLICATION RULES ##



###bspc rule -a Gimp desktop='^8' state=floating follow=on rule -a Brave-browser-beta desktop='^2'
###bspc rule -a mplayer2 state=floating
###bspc rule -a Kupfer.py focus=on
###bspc rule -a Screenkey manage=off
###bspc rule -a Pavucontrol state=floating
###bspc rule -a Spotify state=floating
###bspc rule -a Lxappearance state=floating
###bspc rule -a Gpick state=floating
###bspc rule -a Thunar state=floating
bspc rule -a Spectacle state=floating
